In [ ]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import pandas as pd

Reading package lists... Done
Building dependency tree
Reading state information... Done
fonts-nanum is already the newest version (20170925-1).
0 upgraded, 0 newly installed, 0 to remove and 37 not upgraded.
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 10 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/var/cache/fontconfig: cleaning cache directory
/root/.cache/fontconfig: not cleaning non-existent cache directory
/root/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded



---

# 1. 데이터 수집 및 가공

코로나 **전** 승객수 excel 파일 변수에 저장

In [ ]:
pre_covid_subway=pd.read_excel('/content/Data/data1.xlsx')
pre_covid_subway.head()

  역      명       4월       5월       6월  ...     8월.1     9월.1    10월.1    11월.1
0       장암   109898   117564   113921  ...   116795   105619   118613   112086
1   도봉산(7)   675493   702991   644143  ...   613038   640892   717614   682895
2      수락산   851948   889870   844877  ...   826187   787135   865496   837749
3       마들   728056   751631   703912  ...   705277   692025   761685   748626
4    노원(7)  1329066  1398591  1305919  ...  1343667  1251531  1369487  1349996

[5 rows x 21 columns]

코로나 **후** 승객수 excel 파일 변수에 저장

In [ ]:
post_covid_subway=pd.read_excel('/content/Data/data2.xlsx')
post_covid_subway.head()

  역      명      4월      5월      6월  ...    8월.1    9월.1   10월.1   11월.1
0       장암   58846   63815   66181  ...   56524   57323   62862   65605
1   도봉산(7)  220328  242200  251082  ...  217897  225320  253444  262086
2      수락산  309941  340735  348420  ...  318117  323007  349490  356825
3       마들  275194  300489  316540  ...  302330  304969  332819  352763
4    노원(7)  455755  511893  525438  ...  472922  468680  507923  531016

[5 rows x 21 columns]

In [ ]:
pre_covid_subway['합계']=pre_covid_subway['4월']+pre_covid_subway['5월']+pre_covid_subway['6월']+pre_covid_subway['7월']+pre_covid_subway['8월']+pre_covid_subway['9월']+pre_covid_subway['10월']+pre_covid_subway['11월']+pre_covid_subway['12월']+pre_covid_subway['1월']+pre_covid_subway['2월']+pre_covid_subway['3월']+pre_covid_subway['4월.1']+pre_covid_subway['5월.1']+pre_covid_subway['6월.1']+pre_covid_subway['7월.1']+pre_covid_subway['8월.1']+pre_covid_subway['9월.1']+pre_covid_subway['10월.1']+pre_covid_subway['11월.1']
pre_covid_subway.sort_values(by='합계', ascending=False).head() #합계로내림차순

      역      명       4월       5월       6월  ...     9월.1    10월.1    11월.1        합계
37  가산디지털단지(7)  2410892  2384375  2258195  ...  2218934  2459146  2467699  47732990
39       광명사거리  1658548  1689665  1596516  ...  1485212  1616176  1572788  32028678
38          철산  1515136  1544942  1449245  ...  1381225  1524596  1495131  29623835
4        노원(7)  1329066  1398591  1305919  ...  1251531  1369487  1349996  26886710
22          학동  1340807  1326600  1279477  ...  1237867  1405677  1404703  26477754

[5 rows x 22 columns]

In [ ]:
post_covid_subway['합계']=post_covid_subway['4월']+post_covid_subway['5월']+post_covid_subway['6월']+post_covid_subway['7월']+post_covid_subway['8월']+post_covid_subway['9월']+post_covid_subway['10월']+post_covid_subway['11월']+post_covid_subway['12월']+post_covid_subway['1월']+post_covid_subway['2월']+post_covid_subway['3월']+post_covid_subway['4월.1']+post_covid_subway['5월.1']+post_covid_subway['6월.1']+post_covid_subway['7월.1']+post_covid_subway['8월.1']+post_covid_subway['9월.1']+post_covid_subway['10월.1']+post_covid_subway['11월.1']
post_covid_subway.sort_values(by='합계', ascending=False).head() #합계로내림차순

      역      명      4월       5월       6월  ...    9월.1    10월.1    11월.1        합계
37  가산디지털단지(7)  980214  1023788  1121356  ...  959481  1031376  1163960  21122535
39       광명사거리  560932   612053   619051  ...  544545   590530   620572  11562955
22          학동  505604   531445   584498  ...  494433   545253   619595  10994475
38          철산  512601   559516   579884  ...  501195   539434   578264  10744757
4        노원(7)  455755   511893   525438  ...  468680   507923   531016   9854516

[5 rows x 22 columns]

In [ ]:
pre_covid_subway['평균']=pre_covid_subway['합계']//18
post_covid_subway['평균']=post_covid_subway['합계']//18

In [ ]:
pre_covid_subway['감소인원합계']=pre_covid_subway['합계']-post_covid_subway['합계'] #가장 차이가 많이 나는 5개
pre_covid_subway.sort_values(by='감소인원합계', ascending=False).head() #감소인원합계로내림차순

      역      명       4월       5월       6월  ...    11월.1        합계       평균    감소인원합계
37  가산디지털단지(7)  2410892  2384375  2258195  ...  2467699  47732990  2651832  26610455
39       광명사거리  1658548  1689665  1596516  ...  1572788  32028678  1779371  20465723
38          철산  1515136  1544942  1449245  ...  1495131  29623835  1645768  18879078
4        노원(7)  1329066  1398591  1305919  ...  1349996  26886710  1493706  17032194
20          청담  1310535  1314982  1239777  ...  1313577  25433645  1412980  16183997

[5 rows x 24 columns]

# 코로나 후 가장 승객 수 감소율이 큰 역 5개:

건대입구,어린이대공원,숭실대입구,대림,고속터미널

In [ ]:
pre_covid_subway['감소율']=pre_covid_subway['감소인원합계']/pre_covid_subway['합계']*100
pre_covid_subway.sort_values(by='감소율', ascending=False).head() #감소율로내림차순, 가장 차이가 많은 역 5개

    역      명       4월       5월       6월  ...        합계       평균    감소인원합계        감소율
18   건대입구(7)  1062624  1110224  1001350  ...  20928062  1162670  14633848  69.924525
17    어린이대공원  1189023  1287507   995391  ...  19827926  1101551  13719745  69.194050
29     숭실대입구  1068978  1079721   940768  ...  18998303  1055461  13016729  68.515219
35     대림(7)   654678   669806   633984  ...  13207851   733769   8961203  67.847548
25  고속터미널(7)  1228278  1275509  1170050  ...  24006414  1333689  15927055  66.344998

[5 rows x 25 columns]

In [ ]:
df_max=pd.read_excel('/content/Data/pre_average.xlsx')

# 코로나 후 가장 승객 수 감소율이 작은 역 3개:
장암,천왕,군자

In [ ]:
pre_covid_subway.sort_values(by='감소율', ascending=True).head(3) #감소율로오름차순

   역      명      4월      5월      6월  ...        합계      평균   감소인원합계        감소율
0        장암  109898  117564  113921  ...   2186614  121478   968754  44.303841
40       천왕  534644  539655  512809  ...  10968258  609347  5583429  50.905340
16    군자(7)  762649  811180  781148  ...  16094036  894113  8741349  54.314213

[3 rows x 25 columns]

In [ ]:
df_min=pd.read_excel('/content/Data/post_average.xlsx')

# **월 평균 지하철 이용객 추출**

코로나 전

In [ ]:
pre_covid_subway.iloc[:,[0,21,23,25]].to_excel('pre_average_address.xlsx')
pre_average_address = pd.read_excel('/content/pre_average_address.xlsx')
pre_average_address.head()

IndexError: ignored

In [ ]:
meanrate_pre=pre_average_address['감소율'].mean()
print(meanrate_pre)

코로나 후

In [ ]:
post_covid_subway.iloc[:,[0,21,23]].to_excel('post_average_address.xlsx')
post_average_address = pd.read_excel('/content/post_average_address.xlsx')
post_average_address.head()



---
# 2. 데이터 시각화

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.rc('font', family='NanumBarunGothic')

df_max

코로나 후 가장 승객 수 감소율이 큰 역 5개:

In [ ]:
sns.barplot(x='역명',y='평균',hue='시기',data=df_max)

코로나 후 가장 승객 수 감소율이 작은 역 3개:

In [ ]:
sns.barplot(x='역명',y='평균',hue='시기',data=df_min)

# 코로나 후 지하철 승객 수 감소율 googlemaps에 나타내기

In [ ]:
!pip install googlemaps

import folium
import googlemaps

In [ ]:
gmaps_key='AIzaSyBIiAHtbJ_01yeMB1_UHtZt4UQT7B0HuZo'
gmaps = googlemaps.Client(key=gmaps_key)

In [ ]:
lat = []
lng = []

for n in pre_average_address.index:
        target_name = pre_average_address['주소'][n]
        gmaps_output = gmaps.geocode(target_name)
        location_output = gmaps_output[0].get('geometry')
        lat.append(location_output['location']['lat'])
        lng.append(location_output['location']['lng'])



pre_average_address['lat'] = lat
pre_average_address['lng'] = lng
pre_average_address.head()

In [ ]:
map = folium.Map(location=[37.6049559175497, 127.02],zoom_start=11.4)

maxs=["건대입구(7)","어린이대공원","숭실대입구","대림(7)","고속터미널(7)"]

for n in pre_average_address.index:
  if pre_average_address['감소율'][n]>pre_average_address['감소율'].mean():
    if pre_average_address['역명'][n] in maxs:
          folium.CircleMarker([pre_average_address['lat'][n],pre_average_address['lng'][n]],
          radius=20,color = '	#8B0000	',
          fill_color='#8B0000').add_to(map)
    else:
      folium.CircleMarker([pre_average_address['lat'][n],pre_average_address['lng'][n]],
                      radius=15,color = '	#FF0000	',
                      fill_color='	#FF0000	').add_to(map)
  else:
    folium.CircleMarker([pre_average_address['lat'][n],pre_average_address['lng'][n]],
                      radius=8,color = '	#4169E1',
                      fill_color='	#4169E1').add_to(map)

map